### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by dbaelz** [dbaelz/Konclik#8]
I'd like to release a version 1.0 in the near future. In this issue I want to collect open questions, missing features and further points which should be done by then. Feel free to add them as comments and I'll expand the list when necessary.

### TODO
- [ ] All issues from the 1.0 Milestone: https://github.com/dbaelz/Konclik/milestone/1
- [ ] Konclik is used in a public project as reference
- [ ] Update version in Gradle file

**Comment by dbaelz** [comment]
@DrewCarlson Any suggestions for the 1.0 release? Do you think the library is feature-ready for this step?

**Comment by DrewCarlson** [comment]
I do have a couple of feature and API suggestions to run by you, I will comment them here once I get a chance to think through them today.  Most of the things I've considered adding would work best as additional modules we could add after v1 (ex. cross platform readline, getpass, etc. to eliminate the need for [this](https://github.com/DrewCarlson/Kryptor/blob/7d2002895db96f20fcb34ba55debd1efda9dd4f1/src/macosMain/kotlin/term.kt) and better support all platforms).

I'm trying to get [another project](https://github.com/DrewCarlson/kotlin-mobius) down from 3 CI services to just Travis, if I get Windows working I'll open a PR here.

PS: It is just a demo project (that is totally insecure at the moment), but the Kryptor project I linked could be a good reference project once windows and linux is configured.

**Comment by dbaelz** [comment]
@DrewCarlson Thanks or all your help, PRs and ideas. I'm currently a little bit busy at work and in my private time so "near future" for the 1.0 release might be an exaggeration. More like early to mid November.

I'll take a look on the kotlin-mobius and Kryptor projects and think about the 1.0 feature set by myself. Just add your ideas for (pre) 1.0 features in the comments and we could discuss them here or by mail/chat.

**Comment by DrewCarlson** [comment]
👌 Sounds good!  No rush on releasing, publishing manually is easy.  You're very welcome, Konclik has saved me a lot of time :).

**Comment by DrewCarlson** [comment]
Here are some of the more important things I’d like to see for v1
- Add VarArgument with optional arg count, can only be first or last in the arguments list.
- Support option aliases: Parameter.Option.Value("--times”, “-t”)
- Allow Options to have help text

Another thing I think would be great (though it could wait until after v1) is support for providing a mechanism for precisely typed arguments with verified properties.  Ex. you could define a set of arguments like `listOf(FileArgument(‘input’, exists = true), FileArgument(‘output’, folder = true))` and during argument parsing, `input` would be validated as a file/file path and that it exists and `output` would be validated to be a folder on the system. or a valid folder path.

I'm not saying to add a whole bunch of argument types right now, but it would be worth figuring out the impact on the api when supporting these specialized arguments.

**Comment by dbaelz** [comment]
#### For the 1.0 release
- Support for abbreviations and help pages for parameters was in my mind as well. Help should be easy, abbreviation is more work but doable.
- VarArgument is an interesting idea. I'll open an issue for this in the future, so we could discuss details
- Dokka: Yeah, the library is lacking some code documentation and I'll do it before the 1.0 release

#### Future
- I thought about the challenge to provide the type parameter for the options so that the default value and the parsed args has the correct type are not Strings. The bad side: Type erasure, generics, (in|co)variance and so on. I'm not sure if it's done that easy and without changing everything. Maybe something for a 2.0, maybe earlier :grinning: 
- I'll keep your post 1.0 ideas in mind. Special handling for files is another cool thing for CLI applications and I'm open minded for new/other positional arguments and options.
